### ISSUE TITLE
Anti-virus

### ISSUE THREAD

**Issue by Turbo747JV** [DCS-Skunkworks/Bort#19]
Help,

my anti-virus (McAfee) is deleting the setup program all the time.

**Comment by charliefoxtwo** [comment]
Thanks for reporting this. I'm happy to submit a false-positive report to McAfee. Could you confirm which version of McAfee you have and that the issue is with the bort-0.3.0.Setup.exe file?

Interestingly it's not being reported as malicious by McAfee on VirusTotal, but two other services I've never heard of are reporting false positives so who knows 🤷 https://www.virustotal.com/gui/file/37f663e3f9059990b9c3be242b77c4833d130e34e58178dbfe90ae99b0a18c39

In the meantime, you may be able to restore the file by following these instructions https://www.mcafee.com/support/?articleId=TS100843&page=shell&shell=article-view

**Comment by Turbo747JV** [comment]
Hi Charlie,

 

I’m using McAfee Lifesafe.  But I strongly have the impression that also the default Windows security doesn’t like the file either since I always needed to overrule it’s advice not to run the setup file.

 

Kind regards,

 

Johan Verhoeven

**Comment by charliefoxtwo** [comment]
Windows gives the whole "don't run" suggestion because I don't have a signed developer certificate with them I believe. I have had windows defender report bort as a virus in the past, but I submitted a false positive report and that's since been resolved to my knowledge.

Is there any sort of version number for your McAfee installation? Typically AV companies ask for a version/database/definition number or similar so they can reproduce the issue.

**Comment by Turbo747JV** [comment]
Charlie,

 

I hope this helps :

 



 



 

Kind regards,

 

Johan

**Comment by charliefoxtwo** [comment]
Hey, not sure if you attached an image, but it didn't seem to attach to the github issue.

**Comment by Turbo747JV** [comment]
I’d copied screenshots with the details in the mail.

**Comment by charliefoxtwo** [comment]
I figured, but I cannot see them.

Here is a screenshot of what I see (I don't know if you'll be able to see this in your email):
<img width="950" alt="image" src="https://github.com/DCS-Skunkworks/Bort/assets/30303272/bcaf14b9-6e57-457c-8aab-0d26243bf0a5">

**Comment by Turbo747JV** [comment]
OK, I see.

 

I’ll just write it down :

 

McAfee LifeSafe

Version 1.17.226

Release name 16.0 R117

Affid 1311

Language NL-NL

Last update 03/05/2024

 

Components

Antivirus

Build 1.1.3475.0

Content creation date 04/05/2024

Content version 1766.0

 

Secure VPN

Build 29

Version 1.17

 

Advanced Firewall

Build 40

Version 1.17

 

Hope this helps.

 

Rgds,

 

Johan VERHOEVEN

**Comment by charliefoxtwo** [comment]
That's perfect, thank you! I'll submit a false positive report now.

**Comment by Turbo747JV** [comment]
Didn’t try anymore to be honest.  Used the Virpil Link tool to unlock the lights.

 

Thnx anyhow.
